/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  ApiResponseBoolean,
  ApiResponseLoginResponse,
  ApiResponseString,
  ApiResponseTwoFactorSetupResponse,
  ApiResponseUserResponse,
  Enable2FAWithSecretRequest,
  LoginRequest,
  RefreshTokenRequest,
  RegisterRequest,
  ResendVerificationEmailParams,
  VerifyEmailParams,
} from '../models/auth';

import { customInstance } from '../apiClient';
type SecondParameter<T extends (...args: never) ${DB_USER:***REMOVED***}> unknown> ${DB_USER:***REMOVED***} Parameters<T>[1];

export const resendVerificationEmail ${DB_USER:***REMOVED***} (
  params: ResendVerificationEmailParams,
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    { url: `/auth/resend-verification`, method: 'POST', params },
    options
  );
};

export const register ${DB_USER:***REMOVED***} (
  registerRequest: RegisterRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseUserResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseUserResponse>(
    {
      url: `/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: registerRequest,
    },
    options
  );
};

export const refreshToken ${DB_USER:***REMOVED***} (
  refreshTokenRequest: RefreshTokenRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseLoginResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseLoginResponse>(
    {
      url: `/auth/refresh`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: refreshTokenRequest,
    },
    options
  );
};

export const login ${DB_USER:***REMOVED***} (
  loginRequest: LoginRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseLoginResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseLoginResponse>(
    {
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: loginRequest,
    },
    options
  );
};

export const enable2FA ${DB_USER:***REMOVED***} (
  enable2FAWithSecretRequest: Enable2FAWithSecretRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    {
      url: `/auth/2fa/enable`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: enable2FAWithSecretRequest,
    },
    options
  );
};

export const disable2FA ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    { url: `/auth/2fa/disable`, method: 'POST' },
    options
  );
};

export const getUserById ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseUserResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseUserResponse>(
    { url: `/users/${id}`, method: 'GET' },
    options
  );
};

export const getUserEmail ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<string>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<string>(
    { url: `/users/${id}/email`, method: 'GET' },
    options
  );
};

export const getCurrentUser ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseUserResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseUserResponse>(
    { url: `/users/me`, method: 'GET' },
    options
  );
};

export const verifyEmail ${DB_USER:***REMOVED***} (
  params: VerifyEmailParams,
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    { url: `/auth/verify-email`, method: 'GET', params },
    options
  );
};

export const health ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    { url: `/auth/health`, method: 'GET' },
    options
  );
};

export const get2FAStatus ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseBoolean>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseBoolean>(
    { url: `/auth/2fa/status`, method: 'GET' },
    options
  );
};

export const generateSetup ${DB_USER:***REMOVED***} (
  options?: SecondParameter<
    typeof customInstance<ApiResponseTwoFactorSetupResponse>
  >
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseTwoFactorSetupResponse>(
    { url: `/auth/2fa/setup`, method: 'GET' },
    options
  );
};

export type ResendVerificationEmailResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof resendVerificationEmail>>
>;
export type RegisterResult ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof register>>>;
export type RefreshTokenResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof refreshToken>>
>;
export type LoginResult ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof login>>>;
export type Enable2FAResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof enable2FA>>
>;
export type Disable2FAResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof disable2FA>>
>;
export type GetUserByIdResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getUserById>>
>;
export type GetUserEmailResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getUserEmail>>
>;
export type GetCurrentUserResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getCurrentUser>>
>;
export type VerifyEmailResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof verifyEmail>>
>;
export type HealthResult ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof health>>>;
export type Get2FAStatusResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof get2FAStatus>>
>;
export type GenerateSetupResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof generateSetup>>
>;
