/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AddCartItemRequest,
  ApiResponseCartItemResponse,
  ApiResponseCartResponse,
  ApiResponseDnsRecordResponse,
  ApiResponseDomainResponse,
  ApiResponseListDnsRecordResponse,
  ApiResponseListDomainSearchResult,
  ApiResponseNsDelegationResponse,
  ApiResponseOrderResponse,
  ApiResponsePageDomainResponse,
  ApiResponsePageOrderResponse,
  ApiResponsePageZone,
  ApiResponseString,
  ApiResponseVoid,
  ApiResponseZone,
  CreateARecordRequest,
  CreateAaaaRecordRequest,
  CreateCaaRecordRequest,
  CreateCnameRecordRequest,
  CreateDomainRequest,
  CreateMxRecordRequest,
  CreateOrderRequest,
  CreateSrvRecordRequest,
  CreateTxtRecordRequest,
  CreateZoneRequest,
  GetAllDomainsParams,
  GetAllZonesParams,
  GetOrdersParams,
  NsDelegationRequest,
  SearchDomainsParams,
  UpdateDnsRecordRequest,
  UpdateDomainRequest,
  UpdateOrderStatusParams,
  UpdateZoneRequest,
} from '../models/domain-order';

import { customInstance } from '../apiClientDomains';
type SecondParameter<T extends (...args: never) ${DB_USER:***REMOVED***}> unknown> ${DB_USER:***REMOVED***} Parameters<T>[1];

export const getZoneById ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseZone>(
    { url: `/zones/${id}`, method: 'GET' },
    options
  );
};

export const updateZone ${DB_USER:***REMOVED***} (
  id: string,
  updateZoneRequest: UpdateZoneRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseZone>(
    {
      url: `/zones/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateZoneRequest,
    },
    options
  );
};

export const deleteZone ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseVoid>(
    { url: `/zones/${id}`, method: 'DELETE' },
    options
  );
};

export const updateOrderStatus ${DB_USER:***REMOVED***} (
  id: string,
  params: UpdateOrderStatusParams,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseOrderResponse>(
    { url: `/orders/${id}/status`, method: 'PUT', params },
    options
  );
};

export const getDomainById ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDomainResponse>(
    { url: `/domains/${id}`, method: 'GET' },
    options
  );
};

export const updateDomain ${DB_USER:***REMOVED***} (
  id: string,
  updateDomainRequest: UpdateDomainRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDomainResponse>(
    {
      url: `/domains/${id}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateDomainRequest,
    },
    options
  );
};

export const deleteDomain ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseVoid>(
    { url: `/domains/${id}`, method: 'DELETE' },
    options
  );
};

export const getRecordById ${DB_USER:***REMOVED***} (
  recordId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    { url: `/dns/records/${recordId}`, method: 'GET' },
    options
  );
};

export const updateRecord ${DB_USER:***REMOVED***} (
  recordId: string,
  updateDnsRecordRequest: UpdateDnsRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/${recordId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateDnsRecordRequest,
    },
    options
  );
};

export const deleteRecord ${DB_USER:***REMOVED***} (
  recordId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseVoid>(
    { url: `/dns/records/${recordId}`, method: 'DELETE' },
    options
  );
};

export const getDelegation ${DB_USER:***REMOVED***} (
  domainId: string,
  options?: SecondParameter<
    typeof customInstance<ApiResponseNsDelegationResponse>
  >
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseNsDelegationResponse>(
    { url: `/dns/delegation/domain/${domainId}`, method: 'GET' },
    options
  );
};

export const setDelegation ${DB_USER:***REMOVED***} (
  domainId: string,
  nsDelegationRequest: NsDelegationRequest,
  options?: SecondParameter<
    typeof customInstance<ApiResponseNsDelegationResponse>
  >
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseNsDelegationResponse>(
    {
      url: `/dns/delegation/domain/${domainId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: nsDelegationRequest,
    },
    options
  );
};

export const removeDelegation ${DB_USER:***REMOVED***} (
  domainId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseVoid>(
    { url: `/dns/delegation/domain/${domainId}`, method: 'DELETE' },
    options
  );
};

export const getAllZones ${DB_USER:***REMOVED***} (
  params: GetAllZonesParams,
  options?: SecondParameter<typeof customInstance<ApiResponsePageZone>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponsePageZone>(
    { url: `/zones`, method: 'GET', params },
    options
  );
};

export const createZone ${DB_USER:***REMOVED***} (
  createZoneRequest: CreateZoneRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseZone>(
    {
      url: `/zones`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createZoneRequest,
    },
    options
  );
};

export const getOrders ${DB_USER:***REMOVED***} (
  params: GetOrdersParams,
  options?: SecondParameter<typeof customInstance<ApiResponsePageOrderResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponsePageOrderResponse>(
    { url: `/orders`, method: 'GET', params },
    options
  );
};

export const createOrder ${DB_USER:***REMOVED***} (
  createOrderRequest: CreateOrderRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseOrderResponse>(
    {
      url: `/orders`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createOrderRequest,
    },
    options
  );
};

export const cancelOrder ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseOrderResponse>(
    { url: `/orders/${id}/cancel`, method: 'POST' },
    options
  );
};

export const getAllDomains ${DB_USER:***REMOVED***} (
  params: GetAllDomainsParams,
  options?: SecondParameter<
    typeof customInstance<ApiResponsePageDomainResponse>
  >
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponsePageDomainResponse>(
    { url: `/domains`, method: 'GET', params },
    options
  );
};

export const createDomain ${DB_USER:***REMOVED***} (
  createDomainRequest: CreateDomainRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDomainResponse>(
    {
      url: `/domains`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createDomainRequest,
    },
    options
  );
};

export const activateDomain ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDomainResponse>(
    { url: `/domains/${id}/activate`, method: 'POST' },
    options
  );
};

export const createTxtRecord ${DB_USER:***REMOVED***} (
  createTxtRecordRequest: CreateTxtRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/txt`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTxtRecordRequest,
    },
    options
  );
};

export const createSrvRecord ${DB_USER:***REMOVED***} (
  createSrvRecordRequest: CreateSrvRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/srv`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSrvRecordRequest,
    },
    options
  );
};

export const createMxRecord ${DB_USER:***REMOVED***} (
  createMxRecordRequest: CreateMxRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/mx`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createMxRecordRequest,
    },
    options
  );
};

export const createCnameRecord ${DB_USER:***REMOVED***} (
  createCnameRecordRequest: CreateCnameRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/cname`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCnameRecordRequest,
    },
    options
  );
};

export const createCaaRecord ${DB_USER:***REMOVED***} (
  createCaaRecordRequest: CreateCaaRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/caa`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createCaaRecordRequest,
    },
    options
  );
};

export const createAaaaRecord ${DB_USER:***REMOVED***} (
  createAaaaRecordRequest: CreateAaaaRecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/aaaa`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createAaaaRecordRequest,
    },
    options
  );
};

export const createARecord ${DB_USER:***REMOVED***} (
  createARecordRequest: CreateARecordRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseDnsRecordResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDnsRecordResponse>(
    {
      url: `/dns/records/a`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createARecordRequest,
    },
    options
  );
};

export const addItem ${DB_USER:***REMOVED***} (
  addCartItemRequest: AddCartItemRequest,
  options?: SecondParameter<typeof customInstance<ApiResponseCartItemResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseCartItemResponse>(
    {
      url: `/cart/items`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: addCartItemRequest,
    },
    options
  );
};

export const getZoneByName ${DB_USER:***REMOVED***} (
  name: string,
  options?: SecondParameter<typeof customInstance<ApiResponseZone>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseZone>(
    { url: `/zones/name/${name}`, method: 'GET' },
    options
  );
};

export const getOrderById ${DB_USER:***REMOVED***} (
  id: string,
  options?: SecondParameter<typeof customInstance<ApiResponseOrderResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseOrderResponse>(
    { url: `/orders/${id}`, method: 'GET' },
    options
  );
};

export const searchDomains ${DB_USER:***REMOVED***} (
  params: SearchDomainsParams,
  options?: SecondParameter<
    typeof customInstance<ApiResponseListDomainSearchResult>
  >
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseListDomainSearchResult>(
    { url: `/domains/search`, method: 'GET', params },
    options
  );
};

export const getDomainByFqdn ${DB_USER:***REMOVED***} (
  fqdn: string,
  options?: SecondParameter<typeof customInstance<ApiResponseDomainResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseDomainResponse>(
    { url: `/domains/fqdn/${fqdn}`, method: 'GET' },
    options
  );
};

export const health ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    { url: `/dns/records/health`, method: 'GET' },
    options
  );
};

export const getRecordsByDomain ${DB_USER:***REMOVED***} (
  domainId: string,
  options?: SecondParameter<
    typeof customInstance<ApiResponseListDnsRecordResponse>
  >
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseListDnsRecordResponse>(
    { url: `/dns/records/domain/${domainId}`, method: 'GET' },
    options
  );
};

export const health1 ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseString>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseString>(
    { url: `/dns/delegation/health`, method: 'GET' },
    options
  );
};

export const getCart ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseCartResponse>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseCartResponse>(
    { url: `/cart`, method: 'GET' },
    options
  );
};

export const clearCart ${DB_USER:***REMOVED***} (
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseVoid>(
    { url: `/cart`, method: 'DELETE' },
    options
  );
};

export const removeItem ${DB_USER:***REMOVED***} (
  itemId: string,
  options?: SecondParameter<typeof customInstance<ApiResponseVoid>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<ApiResponseVoid>(
    { url: `/cart/items/${itemId}`, method: 'DELETE' },
    options
  );
};

export type GetZoneByIdResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getZoneById>>
>;
export type UpdateZoneResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof updateZone>>
>;
export type DeleteZoneResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof deleteZone>>
>;
export type UpdateOrderStatusResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof updateOrderStatus>>
>;
export type GetDomainByIdResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getDomainById>>
>;
export type UpdateDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof updateDomain>>
>;
export type DeleteDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof deleteDomain>>
>;
export type GetRecordByIdResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getRecordById>>
>;
export type UpdateRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof updateRecord>>
>;
export type DeleteRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof deleteRecord>>
>;
export type GetDelegationResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getDelegation>>
>;
export type SetDelegationResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof setDelegation>>
>;
export type RemoveDelegationResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof removeDelegation>>
>;
export type GetAllZonesResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getAllZones>>
>;
export type CreateZoneResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createZone>>
>;
export type GetOrdersResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getOrders>>
>;
export type CreateOrderResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createOrder>>
>;
export type CancelOrderResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof cancelOrder>>
>;
export type GetAllDomainsResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getAllDomains>>
>;
export type CreateDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createDomain>>
>;
export type ActivateDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof activateDomain>>
>;
export type CreateTxtRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createTxtRecord>>
>;
export type CreateSrvRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createSrvRecord>>
>;
export type CreateMxRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createMxRecord>>
>;
export type CreateCnameRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createCnameRecord>>
>;
export type CreateCaaRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createCaaRecord>>
>;
export type CreateAaaaRecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createAaaaRecord>>
>;
export type CreateARecordResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof createARecord>>
>;
export type AddItemResult ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof addItem>>>;
export type GetZoneByNameResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getZoneByName>>
>;
export type GetOrderByIdResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getOrderById>>
>;
export type SearchDomainsResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof searchDomains>>
>;
export type GetDomainByFqdnResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getDomainByFqdn>>
>;
export type HealthResult ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof health>>>;
export type GetRecordsByDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getRecordsByDomain>>
>;
export type Health1Result ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof health1>>>;
export type GetCartResult ${DB_USER:***REMOVED***} NonNullable<Awaited<ReturnType<typeof getCart>>>;
export type ClearCartResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof clearCart>>
>;
export type RemoveItemResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof removeItem>>
>;
