/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Exdns HTTP API
 * OpenAPI spec version: 0.1.0
 */
import type {
  DeleteZonesDomain200,
  PostZonesDomain201,
  PutZonesDomain200,
  Zone,
} from '../models/exdns';

import { customInstance } from '../apiClientExdns';
type SecondParameter<T extends (...args: never) ${DB_USER:***REMOVED***}> unknown> ${DB_USER:***REMOVED***} Parameters<T>[1];

/**
 * @summary Get zone
 */
export const getZonesDomain ${DB_USER:***REMOVED***} (
  domain: string,
  options?: SecondParameter<typeof customInstance<Zone>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<Zone>(
    { url: `/zones/${domain}`, method: 'GET' },
    options
  );
};

/**
 * @summary Create zone
 */
export const postZonesDomain ${DB_USER:***REMOVED***} (
  domain: string,
  zone: Zone,
  options?: SecondParameter<typeof customInstance<PostZonesDomain201>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<PostZonesDomain201>(
    {
      url: `/zones/${domain}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: zone,
    },
    options
  );
};

/**
 * @summary Update zone
 */
export const putZonesDomain ${DB_USER:***REMOVED***} (
  domain: string,
  zone: Zone,
  options?: SecondParameter<typeof customInstance<PutZonesDomain200>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<PutZonesDomain200>(
    {
      url: `/zones/${domain}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: zone,
    },
    options
  );
};

/**
 * @summary Delete zone
 */
export const deleteZonesDomain ${DB_USER:***REMOVED***} (
  domain: string,
  options?: SecondParameter<typeof customInstance<DeleteZonesDomain200>>
) ${DB_USER:***REMOVED***}> {
  return customInstance<DeleteZonesDomain200>(
    { url: `/zones/${domain}`, method: 'DELETE' },
    options
  );
};

export type GetZonesDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof getZonesDomain>>
>;
export type PostZonesDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof postZonesDomain>>
>;
export type PutZonesDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof putZonesDomain>>
>;
export type DeleteZonesDomainResult ${DB_USER:***REMOVED***} NonNullable<
  Awaited<ReturnType<typeof deleteZonesDomain>>
>;
