/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Pageable } from './pageable';

export type GetAllDomainsParams ${DB_USER:***REMOVED***} {
  pageable: Pageable;
};
