/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Domain Order Service API
 * OpenAPI spec version: 1.0.0
 */

export type ItemAction ${DB_USER:***REMOVED***} (typeof ItemAction)[keyof typeof ItemAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemAction ${DB_USER:***REMOVED***} {
  register: 'register',
  renew: 'renew',
} as const;
