/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Notification Service API
 * OpenAPI spec version: 1.0.0
 */

export type NotificationType ${DB_USER:***REMOVED***}
  (typeof NotificationType)[keyof typeof NotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType ${DB_USER:***REMOVED***} {
  ORDER_CREATED: 'ORDER_CREATED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  DOMAIN_ACTIVATED: 'DOMAIN_ACTIVATED',
  DOMAIN_EXPIRING_SOON: 'DOMAIN_EXPIRING_SOON',
  DOMAIN_EXPIRED: 'DOMAIN_EXPIRED',
} as const;
