/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Domain Order Service API
 * OpenAPI spec version: 1.0.0
 */

export type OrderStatus ${DB_USER:***REMOVED***} (typeof OrderStatus)[keyof typeof OrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus ${DB_USER:***REMOVED***} {
  created: 'created',
  pending_payment: 'pending_payment',
  paid: 'paid',
  cancelled: 'cancelled',
  failed: 'failed',
} as const;
