/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderItemResponseAction ${DB_USER:***REMOVED***}
  (typeof OrderItemResponseAction)[keyof typeof OrderItemResponseAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderItemResponseAction ${DB_USER:***REMOVED***} {
  register: 'register',
  renew: 'renew',
} as const;
