/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Domain Order Service API
 * OpenAPI spec version: 1.0.0
 */
import type { OrderStatus } from './orderStatus';

export type PutOrdersIdStatusParams ${DB_USER:***REMOVED***} {
  status: OrderStatus;
};
